CREATE TABLE `ho_deceased_cert` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `requester_id` int(11) NOT NULL COMMENT 'citizens.id get fullname',
  `brgy_id` int(11) NOT NULL COMMENT 'citizens.id get fullname',
  `relation_type` int(11) NOT NULL,
  `form_type` int(11) NOT NULL,
  `issue_date` datetime NOT NULL,
  `health_officer_id` int(11) NOT NULL COMMENT 'hr_employees.id. get fullname',
  `health_officer_position` varchar(100) NOT NULL COMMENT 'hr_employees.hr_designation_id, get hr_designation.description',
  `is_approved` int(11) NOT NULL COMMENT '0 = Pending, 1 - Approved',
  `deceased_id` int(11) NOT NULL COMMENT 'citizens.id get fullname',
  `place_of_death_id` int(11) NOT NULL COMMENT 'barangays.id get brgy_name, mun_desc, prov_desc',
  `death_date` datetime NOT NULL,
  `transfer_location` varchar(255) NOT NULL,
  `transfer_add_id` int(11) NOT NULL COMMENT 'barangays.id get brgy_name, mun_desc',
  `cashierd_id` int(11) NOT NULL COMMENT 'cto_cashier_details.id',
  `cashier_id` int(11) NOT NULL COMMENT 'cto_cashier.id',
  `or_no` varchar(100) NOT NULL COMMENT 'cto_cashier.or_no',
  `or_date` date NOT NULL COMMENT 'cto_cashier.cashier_or_date',
  `or_amount` double NOT NULL COMMENT 'Ref-Table: cto_cashier_details.tfc_amount',
  `is_free` int(11) NOT NULL COMMENT '0 = not free, 1 = free',
  `status` int(11) NOT NULL COMMENT '0 = Inactive, 1 = Active',
  `created_by` int(11) NOT NULL,
  `updated_by` int(11) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;