@extends('layouts.admin')
@section('page-title')
{{__('Budget')}}
@endsection
@push('script-page')
@endpush
@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{route('dashboard')}}">{{__('Dashboard')}}</a></li>
<li class="breadcrumb-item">{{__('Budget')}}</li>
@endsection
@section('action-btn')

<div class="float-end">
   <a href="#" id="filter_box" class="btn btn-sm btn-primary action-item" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
   <i class="ti-filter"></i>
   </a>
   <a href="#" data-size="lg" data-url="{{ url('/cbobudget/store') }}" data-ajax-popup="true" data-bs-toggle="tooltip" title="{{__('Manage Budget')}}" class="btn btn-sm btn-primary">
   <i class="ti-plus"></i>
   </a>
</div>
@endsection



@section('content')
<div class="row hide" id="this_is_filter">
   <div class="col-sm-12">
      <div class=" mt-2 " id="multiCollapseExample1">
         <div class="card">
            <div class="card-body">
               <div class="d-flex align-items-center justify-content-end">
                  <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 col-12">
                     <div class="btn-box">
                        {{ Form::text('q', '', array('class' => 'form-control','placeholder'=>'Search...','id'=>'q')) }}
                     </div>
                     
                  </div>
                  <div class="col-auto float-end ms-2">
                     <a href="#" class="btn btn-sm btn-primary" id="btn_search">
                     <span class="btn-inner--icon"><i class="ti-search"></i></span>
                     </a>
                     <a href="#" class="btn btn-sm btn-danger" id="btn_clear">
                     <span class="btn-inner--icon"><i class="ti-trash"></i></span>
                     </a>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<div class="row">
   <div class="col-xl-12">
      <div class="card">
         <div class="card-body table-border-style">
            <div class="table-responsive">
               <table class="table" id="Jq_datatablelist">
                  <thead>
                     <tr>
                        <th>{{__('Sr.No.')}}</th>
                        <th>{{__('Budget Year')}}</th> 
                        <th>{{__('Department')}}</th> 
                        <th>{{__('Division')}}</th>
                        <th>{{__('Quarterly')}}</th>
                        <th>{{__('Annual')}}</th>
                        <!-- <th>{{__('Code')}}</th>
                        <th>{{__('Description')}}</th> -->
                        <!-- <th>{{__('Department')}}</th> -->
                        <!-- <th>{{__('Division')}}</th> -->
                        <!-- <th>{{__('Fund Code')}}</th> -->
                        
                        
                        <!-- <th>{{__('Budget Total')}}</th> -->
                        <!-- <th>{{__('Locked')}}</th> -->
                        <!-- <th>{{__('Generated By')}}</th> -->
                        
                        <th>{{__('Status')}}</th>
                        <!-- <th>{{__('Next Step')}}</th> -->
                        <!-- <th>{{__('Status')}}</th> -->
                        <th>{{__('Action')}}</th>
                     </tr>
                  </thead>
               </table>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- <link rel="stylesheet" href="{{ asset('css/select2.min.css') }}"> -->
<link rel="stylesheet" href="http://code.jquery.com/ui/1.9.1/themes/base/jquery-ui.css">

<link href="http://127.0.0.1:8000/css/select2.min.css" rel="stylesheet">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css" rel="stylesheet"/>


<script src="{{ asset('js/budget.js') }}"></script>

@endsection