<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateCpdoDevelopmentPermitsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('cpdo_development_permits', function (Blueprint $table) {
            $table->id();
            $table->Integer('cdp_control_no')->length(11)->default('0')->comment('generated by system');
            $table->integer('cpdo_module_id')->length(11)->cpmment('ref-Table : cpdo_modules.cpdo_modules_id');
            $table->integer('client_id')->length(11)->comment('ref-Table : client.client_id');
            $table->string('cdp_address')->comment('required Address, ref-table : client.client_id (if client have this details');
            $table->string('cdp_email_address')->comment('required email address, ref-table : client.client_id (if client have this details');
            $table->string('cdp_phone_no')->comment('required Phone No Only, ref-table : client.client_id (if client have this details');
            $table->integer('top_transaction_type_id')->length(11)->cpmment('Ref-Table: cto_top_transaction_type.id');
            $table->integer('tfoc_id')->length(11)->cpmment('ref-Table: cto_tfoc.tfoc_id');
            $table->integer('agl_account_id')->length(11)->cpmment('ref-Table: cto_tfoc.agl_account_id');
            $table->integer('sl_id')->length(11)->cpmment('ref-Table: cto_tfoc.sl_id');
            $table->integer('cdp_excemption')->length(11)->cpmment('this will be Radio button. if this field checked the list of cpdo_development_permit_requirements will be disable');
            $table->double('cdp_total_amount',8,2)->cpmment('Computed amount');
            $table->integer('is_active')->default(0)->nullable();
            $table->integer('created_by');
            $table->integer('updated_by');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('cpdo_development_permits');
    }
}
