@extends('layouts.admin')
@section('page-title')
    {{__('Signing Settings[Electronic & Digital]')}}
@endsection
@push('script-page')
@endpush
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{route('dashboard')}}">{{__('Dashboard')}}</a></li>
    <li class="breadcrumb-item">{{__('Signing Settings[Electronic & Digital]')}}</a></li>
@endsection
@section('action-btn')
    <div class="float-end">
         <a href="#" id="filter_box" class="btn btn-sm btn-primary action-item" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="ti-filter"></i>
        </a>
             <a href="#" data-size="xll" data-url="{{ url('/signing-settings/store') }}" data-ajax-popup="true" data-bs-toggle="tooltip" title="{{__('Manage Signing Setting')}}" class="btn btn-sm btn-primary modal-dialog-scrollable">
            <i class="ti-plus"></i>
        </a>
    </div>
@endsection

@section('content')
   <div class="row" id="this_is_filter">
        <div class="col-sm-12">
            <div class=" mt-2 " id="multiCollapseExample1">
                <div class="card">
                    <div class="card-body">
                        <form method="GET" action="#" accept-charset="UTF-8" id="product_service">
							<div class="d-flex align-items-center justify-content-end">
                                <div class="col-xl-2 col-lg-3 col-md-6 col-sm-12 col-12 pdr-20">
                                    <div class="btn-box">
                                    {{ Form::label('menu_description', 'Menu Description', ['class' => 'fs-6 fw-bold']) }}
                                    {{
                                        Form::select('menu_description', $modules, $value = '', ['id' => 'menu_description', 'class' => 'form-control'])
                                    }}                                 
                                    </div>
                                </div>
								<div class="col-xl-2 col-lg-2 col-md-6 col-sm-12 col-12">
									<div class="btn-box">
                                        {{ Form::label('q', 'Search Here..', ['class' => 'fs-6 fw-bold']) }}
										{{ Form::text('q', '', array('class' => 'form-control','placeholder'=>'Search...','id'=>'q')) }}
									</div>
								</div>
								<div class="col-auto float-end ms-2" style="padding-top: 20px;">
									<a href="#" class="btn btn-sm btn-primary" id="btn_search">
										<span class="btn-inner--icon"><i class="ti-search"></i></span>
									</a>
									<a href="#" class="btn btn-sm btn-danger" id="btn_clear">
										<span class="btn-inner--icon"><i class="ti-trash"></i></span>
									</a>
								</div>
							</div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
    <div class="col-xl-10">
        <div class="card">
            <div class="card-body table-border-style">
                <div class="table-responsive">
                    <table class="table" id="Jq_datatablelist">
                        <thead>
                            <tr>
                                <th>{{__('No')}}</th>
                                <th>{{__('Menu Description')}}</th>
                                <th>{{__('Sub Menu')}}</th>
                                <th>{{__('Section')}}</th>
                                <th>{{__('Variable')}}</th>
                                <th>{{__('Remarks')}}</th>
                                <th>{{__('Generated By')}}</th>
                                <th>{{__('Date')}}</th>
                                <th>{{__('Status')}}</th>
                                <th>{{__('Action')}}</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-2">
        <div id="voucher-card" class="card table-card">
            <div class="card-header">
                <h5 class="w-100">Signature Settings</h5>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group m-form__group">
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="signature_type" id="none" value="0" @if($sign_settings_status == 0) checked @endif>
                                <label class="form-check-label" for="none">None</label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="signature_type" id="e_signature" value="1" @if($sign_settings_status == 1) checked @endif>
                                <label class="form-check-label" for="e_signature">Electronic</label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="signature_type" id="digital_signature" value="2" @if($sign_settings_status == 2) checked @endif>
                                <label class="form-check-label" for="digital_signature">Digital</label>
                            </div>
                           <br>
                                 <input type="button" id="save_sign" value="{{__('Save Changes')}}" class="btn btn-primary btn-sm">
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</div>
    <script src="{{ asset('js/SignApplications.js') }}"></script>
@endsection


